//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicrosoftGraphBot {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MicrosoftGraphBot.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /contacts.
        /// </summary>
        public static string Contacts_Endpoint {
            get {
                return ResourceManager.GetString("Contacts_Endpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversations.
        /// </summary>
        public static string Conversations {
            get {
                return ResourceManager.GetString("Conversations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /conversations.
        /// </summary>
        public static string Conversations_Endpoint {
            get {
                return ResourceManager.GetString("Conversations_Endpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Reports.
        /// </summary>
        public static string DirectReports {
            get {
                return ResourceManager.GetString("DirectReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /directReports.
        /// </summary>
        public static string DirectReports_Endpoint {
            get {
                return ResourceManager.GetString("DirectReports_Endpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /events.
        /// </summary>
        public static string Events_Endpoint {
            get {
                return ResourceManager.GetString("Events_Endpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /drive/root/children.
        /// </summary>
        public static string Files_Endpoint {
            get {
                return ResourceManager.GetString("Files_Endpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /memberOf.
        /// </summary>
        public static string Groups_Endpoint {
            get {
                return ResourceManager.GetString("Groups_Endpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail.
        /// </summary>
        public static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /messages.
        /// </summary>
        public static string Mail_Endpoint {
            get {
                return ResourceManager.GetString("Mail_Endpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        public static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /manager.
        /// </summary>
        public static string Manager_Endpoint {
            get {
                return ResourceManager.GetString("Manager_Endpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Members.
        /// </summary>
        public static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /members.
        /// </summary>
        public static string Members_Endpoint {
            get {
                return ResourceManager.GetString("Members_Endpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notebooks.
        /// </summary>
        public static string Notebooks {
            get {
                return ResourceManager.GetString("Notebooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /notes/notebooks.
        /// </summary>
        public static string Notebooks_Endpoint {
            get {
                return ResourceManager.GetString("Notebooks_Endpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Works With (w/Groups).
        /// </summary>
        public static string People {
            get {
                return ResourceManager.GetString("People", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /people.
        /// </summary>
        public static string People_Endpoint {
            get {
                return ResourceManager.GetString("People_Endpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /photo/$value.
        /// </summary>
        public static string Photo_Endpoint {
            get {
                return ResourceManager.GetString("Photo_Endpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plans.
        /// </summary>
        public static string Plans {
            get {
                return ResourceManager.GetString("Plans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /plans.
        /// </summary>
        public static string Plans_Endpoint {
            get {
                return ResourceManager.GetString("Plans_Endpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /tasks.
        /// </summary>
        public static string Tasks_Endpoint {
            get {
                return ResourceManager.GetString("Tasks_Endpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tending Around.
        /// </summary>
        public static string TrendingAround {
            get {
                return ResourceManager.GetString("TrendingAround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /trendingAround.
        /// </summary>
        public static string TrendingAround_Endpoint {
            get {
                return ResourceManager.GetString("TrendingAround_Endpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Works With.
        /// </summary>
        public static string WorkingWith {
            get {
                return ResourceManager.GetString("WorkingWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /workingWith.
        /// </summary>
        public static string WorkingWith_Endpoint {
            get {
                return ResourceManager.GetString("WorkingWith_Endpoint", resourceCulture);
            }
        }
    }
}
